version: "3.8"

services:
# Контейнер с базой данных
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: always
    networks:
      - internal

  nginx:
    container_name: nginx
    depends_on:
      - postgres
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www/otusha:/var/www
      - ./log/nginx:/var/log/nginx
    restart: always
    networks:
      - internal

# php контейнер
  php:
    container_name: php
    build: 
      context: ./php
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./www/otusha:/var/www
      - ./log/php:/var/log/fpm-php.log
#    command: >
#      bash -c "
#        apk add --no-cache pcre-dev $PHPIZE_DEPS \
#        && pecl install redis \
#        && docker-php-ext-enable redis.so
#      "


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    command: >
      bash -c "
        rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_stream rabbitmq_stream_management &&
        rabbitmq-server
      "
    networks:
      - internal



# redis
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - internal
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
      - REDIS_USER=${DB_USER}
      - REDIS_USER_PASSWORD=${DB_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
#    command: /data/script.sh
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true



  python3101:
    image: python:3.10-slim
    container_name: python3101
    volumes:
      - ./www/otusha/notifier:/app
    working_dir: /app
    ports:
      - "8765:8765"
    command: >
      bash -c "
         set -e &&
         #apt-get update && apt-get install -y libpq-dev gcc &&
         #pip install --upgrade pip &&
         pip install --no-cache-dir psycopg2-binary pika redis  &&
         pip install websockets aio_pika &&
         ls &&
         echo '🚀 Запуск create.py' &&
         python create.py
         echo '🚀 Запуск save2db.py' &&
         python save2db.py &
         echo '🚀 Запуск webserver.py' &&
         python webserver.py &
         wait && echo '✅ Все процессы завершены'
      "

    depends_on:
      - postgres
      - rabbitmq
    environment:
      PYTHONUNBUFFERED: 1
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      MQ_HOST: rabbitmq
      MQ_USER: user
      MQ_PASS: pass
    networks:
      - internal


volumes:
  healthcheck-volume:

# контейнер с сетью
networks:
  internal:
    driver: bridge



